language: python

python:
  - "3.4"

#disable homebrew update

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      language: generic
      env: PYTHON=3.4.8 PYTHON_CONFIGURE_OPTS="--enable-shared" HOMEBREW_NO_AUTO_UPDATE=1

before_install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install upx cmake
    brew install pyenv-virtualenv
    brew tap cartr/qt4
    brew tap-pin cartr/qt4
    brew install qt@4
    brew install qt-webkit@2.3
    pyenv install -l
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

install:
  - pip install apsw
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pip install PySide==1.2.2;
      curl -O https://raw.githubusercontent.com/PySide/pyside-setup/1.2.2/pyside_postinstall.py;
      pyside_postinstall.py -install;
    fi
  - pip install -r requirements.txt

script:
  - cd src/libs/src
  - python setup.py build_ext --inplace
  - mv *.so ..
  - cd ../../..
  - version=`awk '/^VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pyinstaller mac.spec;
      cd dist;
      tar -czvf Krait-v${version}-mac.tar.gz Krait;
    else
      wget https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz;
      tar xJvf upx-3.95-amd64_linux.tar.xz;
      sudo mv upx-3.95-amd64_linux/upx /usr/bin;
      pyinstaller linux.spec;
      cd dist;
      tar -czvf Krait-v${version}-linux.tar.gz Krait;
    fi
  - cd ..

deploy:
  provider: releases
  api_key:
    secure: "ZcYEEAc6cYab6qBXV2ZlW6USOxFBp02Ltg0UZJV/44YRvA+c7oGa6CWElkd1cdejxQK3SJ7KyY8s0klvt+a1ugkeTpVucPEWTzoE/R5evTUFwsG28xzrgrEDdRZPTptXZTaZSmxdEgQn1La4xLmet58Azn4Zmn2lPtZTGRmahkaWz9TeOGSi61LIvAoj0zREyW/pW1B8nZVaCwS/7l8dyNxJIgaxxS3RpTyMNEGzpy29uHiuUJYif6THBDMB3gKbYOaX1QRm51Iy9YuC/gR3ksuSkrb18tDfOApuGyF6Nxed/34ss6ltCr5OK+Wn1f8jxF5wNSpxKqZOP5rYbeHqxa5OOYrkkrL5R8p59tTkdiNlik8K+9GVNtRychCgD/eYDs2V9eEWV82c83pIM/6bDyJlXJ8oOO5Zw7A9g3wG+kOTEbAgSbp4H/hczr8GK27XSt4q/JOspTKyd6IGUMiDC1eCFnv/znldr9q2x48/0dQwClS2Lwl+leIR6v3M54DE1EwMsc+nKFdsf8ImDFmF9z/5bboU8wB3btLE3pf8iB/+GZAzfvPaJ0ZQWdNKVmlac+1+IU+x+8Zza6xztDyIgw+C4LUGI8SKCw3eI0CG1Hrl0EW9UXVOja4rQjc75taL9A5BZBd4eA22nlRXqQtAcWEnzelB+z4CCRvqzuWTqlw="
  file_glob: true
  file: dist/Krait-*.tar.gz
  skip_cleanup: true
  on:
    tags: true
